<?php defined('BASEPATH') OR exit('No direct script access allowed');
$csrf_name = $this->security->get_csrf_token_name(); $csrf_hash = $this->security->get_csrf_hash();
$total_pages = max(1, (int)ceil($total / $per_page));
$can_moderate_sellers = in_array('*', $permissions ?? array(), true)
    || in_array('marketplace.moderate_sellers', $permissions ?? array(), true);
$can_moderate_listings = in_array('*', $permissions ?? array(), true)
    || in_array('marketplace.moderate_listings', $permissions ?? array(), true);
?>
<div class="row justify-between mb-4" style="flex-wrap:wrap;gap:.75rem"><div><h2 class="card-title mb-0">Marketplace operations</h2><p class="muted text-sm"><?=number_format($total)?> result(s)</p></div><form method="get" action="<?=site_url('admin/marketplace')?>" class="row" style="gap:.4rem"><input type="hidden" name="tab" value="<?=htmlspecialchars($tab)?>"><input class="input" name="q" value="<?=htmlspecialchars((string)$filters['search'])?>" placeholder="Search reference or title"><input class="input" name="status" value="<?=htmlspecialchars((string)$filters['status'])?>" placeholder="Status"><button class="btn btn-secondary btn-sm">Filter</button></form></div>
<div class="row mb-4" style="gap:.4rem"><?php foreach (array('orders'=>'Escrow orders','sellers'=>'Sellers','listings'=>'Listings') as $key=>$label): ?><a class="btn btn-sm <?=$tab === $key ? 'btn-primary' : 'btn-ghost'?>" href="<?=site_url('admin/marketplace?tab='.$key)?>"><?=$label?></a><?php endforeach; ?></div>
<div class="card overflow-x-auto">
<?php if (empty($rows)): ?><p class="muted">No records match this filter.</p>
<?php elseif ($tab === 'orders'): ?><table class="table"><thead><tr><th>Order</th><th>Listing</th><th>Buyer</th><th>Seller</th><th class="text-right">Gross</th><th>Status</th><th>Created</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><a class="mono text-xs" href="<?=site_url('admin/marketplace/orders/'.$row->public_id)?>"><?=htmlspecialchars($row->public_id)?></a></td><td><?=htmlspecialchars((string)$row->listing_title)?></td><td><?=htmlspecialchars((string)$row->buyer_username)?></td><td><?=htmlspecialchars((string)$row->seller_username)?></td><td class="text-right"><?=windels_money($row->gross_amount)?></td><td><span class="badge badge-default"><?=htmlspecialchars($row->status)?></span></td><td class="text-xs muted"><?=htmlspecialchars($row->created_at)?></td></tr><?php endforeach; ?></tbody></table>
<?php elseif ($tab === 'sellers'): ?><table class="table"><thead><tr><th>Seller</th><th>User</th><th>Status</th><th>Applied</th><th>Moderate</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><strong><?=htmlspecialchars($row->display_name)?></strong><div class="mono text-xs muted"><?=htmlspecialchars($row->public_id)?></div></td><td><?=htmlspecialchars((string)$row->username)?><div class="text-xs muted"><?=htmlspecialchars((string)$row->email)?></div></td><td><span class="badge badge-default"><?=htmlspecialchars($row->status)?></span></td><td class="text-xs muted"><?=htmlspecialchars($row->created_at)?></td><td><?php if ($can_moderate_sellers): ?><form method="post" action="<?=site_url('admin/marketplace/sellers/'.$row->public_id.'/moderate')?>" class="row" style="gap:.3rem;flex-wrap:wrap"><input type="hidden" name="<?=$csrf_name?>" value="<?=$csrf_hash?>"><input class="input" name="note" value="<?=htmlspecialchars((string)$row->admin_note)?>" placeholder="Review note"><select class="select" name="status"><option>APPROVED</option><option>SUSPENDED</option><option>REJECTED</option></select><button class="btn btn-secondary btn-sm">Save</button></form><?php else: ?><span class="muted">—</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table>
<?php else: ?><table class="table"><thead><tr><th>Listing</th><th>Seller</th><th>Price</th><th>Stock</th><th>Status</th><th>Moderate</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><strong><?=htmlspecialchars($row->title)?></strong><div class="mono text-xs muted"><?=htmlspecialchars($row->public_id)?></div><div class="text-xs muted"><?=htmlspecialchars(mb_strimwidth($row->description, 0, 120, '…'))?></div></td><td><?=htmlspecialchars((string)$row->seller_name)?></td><td><?=windels_money($row->price)?></td><td><?=$row->stock === null ? '∞' : (int)$row->stock?></td><td><span class="badge badge-default"><?=htmlspecialchars($row->status)?></span></td><td><?php if ($can_moderate_listings): ?><form method="post" action="<?=site_url('admin/marketplace/listings/'.$row->public_id.'/moderate')?>" class="row" style="gap:.3rem;flex-wrap:wrap"><input type="hidden" name="<?=$csrf_name?>" value="<?=$csrf_hash?>"><input class="input" name="note" value="<?=htmlspecialchars((string)$row->moderation_note)?>" placeholder="Review note"><select class="select" name="status"><option>ACTIVE</option><option>REJECTED</option><option>PAUSED</option><option>ARCHIVED</option></select><button class="btn btn-secondary btn-sm">Save</button></form><?php else: ?><span class="muted">—</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
</div>
<?php if ($total_pages > 1): ?><div class="row justify-between mt-4"><?=$page > 1 ? '<a class="btn btn-ghost btn-sm" href="'.site_url('admin/marketplace?'.http_build_query(array('tab'=>$tab,'page'=>$page-1,'status'=>$filters['status'],'q'=>$filters['search']))).'">← Previous</a>' : '<span></span>'?><span class="muted text-sm">Page <?=$page?> of <?=$total_pages?></span><?=$page < $total_pages ? '<a class="btn btn-ghost btn-sm" href="'.site_url('admin/marketplace?'.http_build_query(array('tab'=>$tab,'page'=>$page+1,'status'=>$filters['status'],'q'=>$filters['search']))).'">Next →</a>' : '<span></span>'?></div><?php endif; ?>
