<?php defined('BASEPATH') OR exit('No direct script access allowed');
$csrf = '<input type="hidden" name="'.htmlspecialchars($this->security->get_csrf_token_name()).'" value="'.htmlspecialchars($this->security->get_csrf_hash()).'">';
$can_reveal = in_array('*', $permissions ?? array(), true)
    || in_array('marketplace.reveal', $permissions ?? array(), true);
$can_resolve = in_array('*', $permissions ?? array(), true)
    || in_array('marketplace.resolve', $permissions ?? array(), true);
?>
<div class="row justify-between mb-4"><a class="btn btn-ghost btn-sm" href="<?=site_url('admin/marketplace')?>">← Marketplace queue</a><span class="badge badge-default"><?=htmlspecialchars($order->status)?></span></div>
<div style="display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:1rem">
<div><div class="card mb-4"><h2 class="card-title"><?=htmlspecialchars((string)$order->listing_title)?></h2><dl class="text-sm" style="display:grid;grid-template-columns:11rem 1fr;gap:.6rem"><dt class="muted">Order</dt><dd class="mono"><?=htmlspecialchars($order->public_id)?></dd><dt class="muted">Buyer</dt><dd><?=htmlspecialchars((string)$order->buyer_username)?> (#<?=(int)$order->buyer_id?>)</dd><dt class="muted">Shipping</dt><dd><?=marvy_money($order->shipping_cost ?? '0')?></dd><dt class="muted">Gross (platform revenue)</dt><dd><?=marvy_money($order->gross_amount)?></dd><dt class="muted">Created</dt><dd><?=htmlspecialchars($order->created_at)?></dd><dt class="muted">Delivered</dt><dd><?=htmlspecialchars((string)$order->delivered_at ?: '—')?></dd><dt class="muted">Release due</dt><dd><?=htmlspecialchars((string)$order->release_due_at ?: '—')?></dd></dl></div>
<?php if ($shipment): ?><div class="card mb-4"><h3 class="card-title">Physical shipment</h3><p class="text-sm mb-2"><span class="badge badge-default"><?=htmlspecialchars($shipment->status)?></span><?php if ($shipment->carrier): ?> · <?=htmlspecialchars($shipment->carrier)?><?php endif; ?><?php if ($shipment->tracking_number): ?> · <span class="mono"><?=htmlspecialchars($shipment->tracking_number)?></span><?php endif; ?></p><p class="text-sm muted mb-2">The shipment record owns tracking and delivery state. <a href="<?=site_url('admin/shop/shipments/'.$shipment->public_id)?>">Open shipment operations →</a></p><?php if ($shipment->tracking_url): ?><a href="<?=htmlspecialchars($shipment->tracking_url)?>" target="_blank" rel="noopener noreferrer">Open tracking link</a><?php endif; ?></div><?php endif; ?>
<?php if ($order->status === 'DISPUTED'): ?><div class="alert alert-warning"><strong>Buyer dispute:</strong><br><?=nl2br(htmlspecialchars((string)$order->dispute_reason))?></div><?php endif; ?>
<?php if ($order->delivery_encrypted): ?><div class="card mb-4"><h3 class="card-title">Encrypted fulfilment</h3><?php if ($plain !== null): ?><pre style="white-space:pre-wrap;overflow-wrap:anywhere;background:#f8fafc;padding:1rem;border-radius:.5rem"><?=htmlspecialchars($plain)?></pre><p class="text-xs muted">Sensitive access was added to the audit log.</p><?php else: ?><p class="text-sm muted">Not loaded into this page. Revealing requires the separate marketplace.reveal permission and records the operator.</p><?php if ($can_reveal): ?><form method="post" action="<?=site_url('admin/marketplace/orders/'.$order->public_id.'/reveal')?>"><?=$csrf?><button class="btn btn-secondary" type="submit">Reveal fulfilment</button></form><?php endif; ?><?php endif; ?></div><?php endif; ?>
<div class="card"><h3 class="card-title">Timeline</h3><?php foreach ($events as $event): ?><div class="text-sm mb-2"><strong><?=htmlspecialchars($event->event_type)?></strong> <span class="muted"><?=htmlspecialchars($event->created_at)?> · <?=htmlspecialchars((string)$event->from_status)?> → <?=htmlspecialchars((string)$event->to_status)?></span><?php if ($event->note): ?><div class="text-xs muted"><?=htmlspecialchars($event->note)?></div><?php endif; ?></div><?php endforeach; ?></div></div>
<aside><?php if ($can_manage && $order->status === 'PAID' && !$shipment): ?><div class="card mb-4"><h3 class="card-title">Fulfil this order</h3><p class="text-xs muted">Fulfilment is platform-side only: no vendor touches this order. Codes, credentials and instructions are encrypted before storage.</p><form method="post" action="<?=site_url('admin/marketplace/orders/'.$order->public_id.'/deliver')?>"><?=$csrf?><textarea class="textarea mb-3" name="delivery" minlength="3" maxlength="20000" rows="8" required></textarea><button class="btn btn-primary" type="submit">Deliver securely</button></form></div><?php endif; ?>
<?php if ($can_resolve && in_array($order->status, array('PAID','DELIVERED','DISPUTED','PARTIALLY_REFUNDED'), true)): ?><div class="card"><h3 class="card-title">Resolve escrow</h3><p class="text-xs muted">Completing the sale closes escrow in the platform favour. Refund returns the buyer's original charge. Both actions are guarded against duplicate money movement and audited.</p><form method="post" action="<?=site_url('admin/marketplace/orders/'.$order->public_id.'/resolve')?>"><?=$csrf?><label class="label">Resolution</label><select class="select mb-3" name="resolution" required><option value="">Choose…</option><?php if (in_array($order->status, array('DELIVERED','DISPUTED'), true) && (!$shipment || $shipment->status === 'DELIVERED')): ?><option value="RELEASE">Complete the sale</option><?php endif; ?><option value="REFUND">Refund buyer in full</option><option value="PARTIAL_REFUND">Refund part of it…</option></select><p class="text-xs muted mb-2">Refundable now: <strong><?=htmlspecialchars($refundable)?></strong><?php if (bccomp((string)($order->refunded_amount ?? '0'), '0', 8) > 0): ?> · already returned: <?=htmlspecialchars(number_format((float)$order->refunded_amount, 2))?><?php endif; ?></p><label class="label">Amount (part refunds only)</label><input class="input mb-2" name="amount" inputmode="decimal" placeholder="e.g. 1500.00"><p class="text-xs muted mb-2">A part refund leaves the buyer's access in place — they keep what they part-paid for. Only refunding the last of the money revokes downloads and returns the remaining stock.</p><label class="label">Units back on the shelf</label><input class="input mb-3" name="restock" type="number" min="0" max="<?=(int)$order->quantity?>" value="0"><label class="label">Reason</label><textarea class="textarea mb-3" name="reason" maxlength="1000" rows="4"></textarea><button class="btn btn-primary" type="submit">Apply resolution</button></form></div><?php elseif (in_array($order->status, array('PAID','DELIVERED','DISPUTED','PARTIALLY_REFUNDED'), true)): ?><div class="card"><h3 class="card-title">Escrow review</h3><p class="text-sm muted">You can review this order, but marketplace.resolve permission is required to release or refund it.</p></div><?php else: ?><div class="card"><h3 class="card-title">Resolved</h3><p class="text-sm muted">No escrow action is available for a <?=htmlspecialchars(strtolower($order->status))?> order.</p></div><?php endif; ?></aside>
</div>
