#!/usr/bin/env node
'use strict';
/**
 * import_sql.mjs — feed a MySQL dump to the dev database over the wire.
 *
 * DEV TOOLING ONLY. `database/marvysocials.sql` is what an operator imports
 * through phpMyAdmin, and nothing in this repository had ever executed it:
 * the file was generated by one script and checked by another that reads it as
 * text. A dump that parses is not a dump that applies.
 *
 * This speaks the MySQL client protocol (the same one CodeIgniter uses), so
 * the statements go through the translator exactly as the application's would.
 *
 *   node tools/devdb/import_sql.mjs --port 3410 --file database/marvysocials.sql
 */
const net = require('node:net');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const argv = process.argv.slice(2);
const arg = (name, def) => { const i = argv.indexOf(name); return i === -1 ? def : argv[i + 1]; };
const PORT = parseInt(arg('--port', '3399'), 10);
const HOST = arg('--host', '127.0.0.1');
const FILE = path.resolve(arg('--file', 'database/marvysocials.sql'));

/* ------------------------------ wire helpers ------------------------------ */

function packet(payload, sequence) {
  const header = Buffer.alloc(4);
  header.writeUIntLE(payload.length, 0, 3);
  header[3] = sequence;
  return Buffer.concat([header, payload]);
}

/** HandshakeResponse41 with mysql_native_password (empty password accepted). */
function handshakeResponse(user, database, salt) {
  const caps = 0x00000200 | 0x00008000 | 0x00000008 | 0x00080000 | 0x00000001;
  const head = Buffer.alloc(32);
  head.writeUInt32LE(caps, 0);
  head.writeUInt32LE(16777215, 4);
  head[8] = 45; // utf8mb4
  const parts = [head, Buffer.from(user + '\0', 'utf8'), Buffer.from([0])];
  if (database) parts.push(Buffer.from(database + '\0', 'utf8'));
  void salt;
  void crypto;
  return Buffer.concat(parts);
}

/**
 * Split a dump into statements.
 *
 * Naive splitting on ';' breaks on semicolons inside strings and comments,
 * which a seed file full of JSON defaults is guaranteed to contain.
 */
function statements(sql) {
  const out = [];
  let buf = '';
  let inSingle = false, inDouble = false, inBacktick = false, inLineComment = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    const next = sql[i + 1];
    if (inLineComment) { if (c === '\n') { inLineComment = false; buf += c; } continue; }
    if (!inSingle && !inDouble && !inBacktick && c === '-' && next === '-') { inLineComment = true; i++; continue; }
    if (!inSingle && !inDouble && !inBacktick && c === '/' && next === '*') {
      const end = sql.indexOf('*/', i + 2);
      i = end === -1 ? sql.length : end + 1;
      continue;
    }
    if (c === "'" && !inDouble && !inBacktick && sql[i - 1] !== '\\') inSingle = !inSingle;
    else if (c === '"' && !inSingle && !inBacktick && sql[i - 1] !== '\\') inDouble = !inDouble;
    else if (c === '`' && !inSingle && !inDouble) inBacktick = !inBacktick;

    if (c === ';' && !inSingle && !inDouble && !inBacktick) {
      const stmt = buf.trim();
      if (stmt) out.push(stmt);
      buf = '';
      continue;
    }
    buf += c;
  }
  const tail = buf.trim();
  if (tail) out.push(tail);
  return out;
}

/* -------------------------------- the run --------------------------------- */

const sql = fs.readFileSync(FILE, 'utf8');
const list = statements(sql);
console.log(`file: ${FILE}`);
console.log(`statements: ${list.length}`);

const socket = net.connect(PORT, HOST);
let sequence = 0;
let stage = 'handshake';
let index = 0;
let failed = 0;
const errors = [];
let buffer = Buffer.alloc(0);

function send(payload) {
  sequence = (sequence + 1) % 256;
  socket.write(packet(payload, sequence));
}
function query(text) {
  sequence = -1;
  send(Buffer.concat([Buffer.from([0x03]), Buffer.from(text, 'utf8')]));
}
function next() {
  if (index >= list.length) {
    console.log(`applied: ${list.length - failed}`);
    console.log(`failed: ${failed}`);
    for (const e of errors.slice(0, 10)) console.log('  ! ' + e);
    socket.end();
    process.exit(failed ? 1 : 0);
  }
  query(list[index++]);
}

socket.on('data', (chunk) => {
  buffer = Buffer.concat([buffer, chunk]);
  while (buffer.length >= 4) {
    const len = buffer.readUIntLE(0, 3);
    if (buffer.length < 4 + len) return;
    const payload = buffer.subarray(4, 4 + len);
    const seq = buffer[3];
    buffer = buffer.subarray(4 + len);

    if (stage === 'handshake') {
      sequence = seq;
      send(handshakeResponse('root', 'marvysocials', null));
      stage = 'auth';
      continue;
    }
    if (stage === 'auth') {
      if (payload[0] === 0xff) {
        console.error('auth failed:', payload.subarray(3).toString('utf8'));
        process.exit(2);
      }
      stage = 'query';
      next();
      continue;
    }
    // Query response: OK (0x00), ERR (0xff) or a result set we can discard.
    if (payload[0] === 0xff) {
      failed++;
      errors.push(list[index - 1].slice(0, 90).replace(/\s+/g, ' ')
                  + ' -> ' + payload.subarray(9).toString('utf8').slice(0, 120));
      next();
    } else if (payload[0] === 0x00 || payload[0] === 0xfe) {
      next();
    }
    // Column/row packets are ignored; the terminating EOF/OK moves us on.
  }
});

socket.on('error', (e) => { console.error('connection error:', e.message); process.exit(2); });
