<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Migration_Identity extends CI_Migration {
 public function up(){
  $this->db->query("CREATE TABLE IF NOT EXISTS price_groups (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $this->db->query("CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(26) NOT NULL UNIQUE, username VARCHAR(64) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NULL, last_name VARCHAR(100) NULL, phone VARCHAR(32) NULL, avatar_url VARCHAR(512) NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', role VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER', price_group_id BIGINT UNSIGNED NULL, referral_code VARCHAR(32) NULL UNIQUE, referred_by_id BIGINT UNSIGNED NULL, email_verified_at DATETIME NULL, last_login_at DATETIME NULL, mfa_enabled TINYINT(1) NOT NULL DEFAULT 0, mfa_secret VARCHAR(255) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_users_status_created (status, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $this->db->query("CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL UNIQUE, description VARCHAR(255) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $this->db->query("CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, perm_key VARCHAR(128) NOT NULL UNIQUE, description VARCHAR(255) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $this->db->query("CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY (role_id, permission_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $this->db->query("CREATE TABLE IF NOT EXISTS user_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL, ip VARCHAR(45) NULL, user_agent VARCHAR(512) NULL, expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_sess_user_exp (user_id, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $this->db->query("CREATE TABLE IF NOT EXISTS login_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NULL, ip VARCHAR(45) NOT NULL, success TINYINT(1) NOT NULL, reason VARCHAR(255) NULL, user_agent VARCHAR(512) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_la_ip_created (ip, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 }
 public function down(){ $this->db->query("DROP TABLE IF EXISTS login_attempts, user_sessions, role_permissions, permissions, roles, users, price_groups"); }
}
