<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Database connection — entirely from .env.
 *
 * The five values a migration to another cPanel account actually changes are
 * VP_DB_HOST, VP_DB_PORT, VP_DB_NAME, VP_DB_USER and VP_DB_PASS. Nothing here
 * is generated by an installer and nothing is written back to disk, so moving
 * hosts is: import database/windels_panel.sql through phpMyAdmin, edit .env, done.
 */
require_once APPPATH.'core/Env.php';
Env::bootstrap(rtrim(realpath(APPPATH.'..'), DIRECTORY_SEPARATOR));

if (!function_exists('windels_db_stricton')) {
    /**
     * Resolve VP_DB_STRICT into the value CI3's drivers expect.
     *
     * Returning NULL (rather than TRUE/FALSE) makes CI3 skip the sql_mode
     * connection init command entirely — the only way to connect to a server
     * that refuses session-level SET.
     *
     * @return bool|null
     */
    function windels_db_stricton() {
        $raw = Env::get('DB_STRICT', null);
        if ($raw === null || $raw === '') return TRUE;
        $norm = strtolower(trim((string) $raw));
        if (in_array($norm, array('inherit', 'server', 'none', 'skip'), TRUE)) return NULL;
        return !in_array($norm, array('0', 'false', 'off', 'no'), TRUE);
    }
}

$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
    'dsn'      => Env::get('DB_DSN', ''),
    // localhost, not a container hostname: on shared hosting MySQL is always
    // local, and a default of "mysql" makes the first page load a DNS failure.
    'hostname' => Env::get('DB_HOST', 'localhost'),
    'port'     => Env::get_int('DB_PORT', 3306),
    'username' => Env::get('DB_USER', ''),
    'password' => Env::get('DB_PASSWORD', ''),
    'database' => Env::get('DB_NAME', ''),
    'dbdriver' => Env::get('DB_DRIVER', 'mysqli'),
    'dbprefix' => '',
    'pconnect' => FALSE,
    // Stay silent on connect failure so /setup and /health/live can report
    // "cannot connect" instead of CodeIgniter's fatal database page. Query
    // debugging is re-enabled after a successful connect in windels_load_database().
    'db_debug' => FALSE,
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => Env::get('DB_CHARSET', 'utf8mb4'),
    'dbcollat' => Env::get('DB_COLLATION', 'utf8mb4_unicode_ci'),
    'swap_pre' => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    // Shared hosting runs whatever sql_mode the host chose. STRICT_ALL_TABLES
    // stays on because the schema relies on it (a truncated DECIMAL(20,8) is a
    // money bug), but it is switchable for hosts that refuse the SET.
    //
    // Three states, because "on" and "off" are not the only useful answers:
    //   true  (default) — force STRICT_ALL_TABLES on every connection
    //   false           — actively strip strict mode from the session
    //   "inherit"       — send no sql_mode statement at all and use whatever
    //                     the server is configured with. CI3 issues its
    //                     sql_mode change as a *connection init command*;
    //                     managed MySQL instances and proxies that disallow
    //                     session-level SET then fail the connect outright
    //                     rather than the query. Leaving stricton unset is the
    //                     documented CI3 way to skip it.
    'stricton' => windels_db_stricton(),
    'failover' => array(),
    'save_queries' => TRUE
);
