<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Database connection — entirely from .env.
 *
 * The five values a migration to another cPanel account actually changes are
 * VP_DB_HOST, VP_DB_PORT, VP_DB_NAME, VP_DB_USER and VP_DB_PASS. Nothing here
 * is generated by an installer and nothing is written back to disk, so moving
 * hosts is: import database/production.sql through phpMyAdmin, edit .env, done.
 */
require_once APPPATH.'core/Env.php';
Env::bootstrap(rtrim(realpath(APPPATH.'..'), DIRECTORY_SEPARATOR));

$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
    'dsn'      => '',
    // localhost, not a container hostname: on shared hosting MySQL is always
    // local, and a default of "mysql" makes the first page load a DNS failure.
    'hostname' => Env::get('DB_HOST', 'localhost'),
    'port'     => Env::get_int('DB_PORT', 3306),
    'username' => Env::get('DB_USER', ''),
    'password' => Env::get('DB_PASSWORD', ''),
    'database' => Env::get('DB_NAME', ''),
    'dbdriver' => Env::get('DB_DRIVER', 'mysqli'),
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => Env::get('DB_CHARSET', 'utf8mb4'),
    'dbcollat' => Env::get('DB_COLLATION', 'utf8mb4_unicode_ci'),
    'swap_pre' => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    // Shared hosting runs whatever sql_mode the host chose. STRICT_ALL_TABLES
    // stays on because the schema relies on it (a truncated DECIMAL(20,8) is a
    // money bug), but it is switchable for hosts that refuse the SET.
    'stricton' => Env::get_bool('DB_STRICT', TRUE),
    'failover' => array(),
    'save_queries' => TRUE
);
